# Generated by Django 5.2.15 on 2026-06-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Если заполнено и больше текущей — показывается скидка.', max_digits=10, null=True, verbose_name='Старая цена, сом'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='Имя автора')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='shop.customer', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='Имя автора')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Ответ магазина')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='shop.customer', verbose_name='Покупатель')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shop.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Ответ на отзыв',
                'verbose_name_plural': 'Ответы на отзывы',
                'ordering': ['created_at'],
            },
        ),
    ]
