# Generated by Django 5.2.15 on 2026-06-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_old_price_review_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Пароль (хеш)'),
        ),
    ]
