# Generated by Django 5.2.15 on 2026-06-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код сброса'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reset_code_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код запрошен'),
        ),
    ]
