# Generated by Django 5.2.15 on 2026-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_broadcast_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Premium-подписка'),
        ),
        migrations.AddField(
            model_name='customer',
            name='premium_until',
            field=models.DateTimeField(blank=True, help_text='Пусто при включённой подписке = бессрочный премиум.', null=True, verbose_name='Premium активен до'),
        ),
        migrations.AddField(
            model_name='product',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сниженная цена для премиум-покупателей. Если пусто — премиум платит обычную цену.', max_digits=10, null=True, verbose_name='Цена для Premium, сом'),
        ),
    ]
