# Generated by Django 5.2.15 on 2026-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_customer_is_premium_customer_premium_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название (кыргызча)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(blank=True, verbose_name='Описание (кыргызча)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Название (English)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ky',
            field=models.CharField(blank=True, max_length=160, verbose_name='Название (кыргызча)'),
        ),
    ]
