# Generated by Django 5.2.15 on 2026-07-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_name_en_category_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Снимок закупочной цены на момент заказа.', max_digits=10, verbose_name='Себестоимость, сом'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.CharField(blank=True, help_text='Напр. «Цвет: Чёрный · Модель: Pro».', max_length=255, verbose_name='Выбранные варианты'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Закупочная цена — используется для расчёта прибыли.', max_digits=10, verbose_name='Себестоимость, сом'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(help_text='Напр. «Цвет», «Модель», «Размер».', max_length=40, verbose_name='Группа')),
                ('value', models.CharField(help_text='Напр. «Чёрный», «Pro», «M».', max_length=80, verbose_name='Значение')),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, help_text='На сколько дороже базовой цены (может быть 0).', max_digits=10, verbose_name='Надбавка к цене, сом')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
