# Generated by Django 5.2.15 on 2026-07-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_cost_orderitem_options_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='options/', verbose_name='Фото (загрузка)'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Фото (ссылка)'),
        ),
    ]
