# Generated by Django 5.2.15 on 2026-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productoption_image_productoption_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Фото выбранного варианта на момент заказа.', max_length=500, verbose_name='Фото (снимок)'),
        ),
    ]
