# Generated by Django 5.2.15 on 2026-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='group',
            field=models.CharField(help_text='Тип выбора: «Цвет», «Размер» или «Модель».', max_length=40, verbose_name='Что выбирают'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото товара в этом варианте (для цвета — фото в этом цвете). Покупатель листает эти фото.', null=True, upload_to='options/', verbose_name='Фото варианта'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='image_url',
            field=models.URLField(blank=True, help_text='Необязательно. Если проще вставить ссылку на фото.', max_length=500, verbose_name='Фото по ссылке'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок показа (0, 1, 2…). Можно оставить 0.', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='На сколько этот вариант дороже обычной цены. 0 — та же цена. Например 200 — на 200 сом дороже.', max_digits=10, verbose_name='Доплата, сом'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='value',
            field=models.CharField(help_text='Например: «Чёрный», «Белый», «M», «Pro».', max_length=80, verbose_name='Вариант'),
        ),
    ]
